kotlinx.coroutines.CancellableContinuation
<kotlinx.coroutines.CancellableContinuation: void completeResume(java.lang.Object)>
<kotlinx.coroutines.CancellableContinuation: void invokeOnCancellation(kotlin.jvm.functions.Function1)>
<kotlinx.coroutines.CancellableContinuation: void resume(java.lang.Object,kotlin.jvm.functions.Function1)>
<kotlinx.coroutines.CancellableContinuation: void resumeUndispatched(kotlinx.coroutines.CoroutineDispatcher,java.lang.Object)>
<kotlinx.coroutines.CancellableContinuation: java.lang.Object tryResume(java.lang.Object,java.lang.Object)>
<kotlinx.coroutines.CancellableContinuation: java.lang.Object tryResume(java.lang.Object,java.lang.Object,kotlin.jvm.functions.Function1)>
<kotlinx.coroutines.CancellableContinuation: java.lang.Object tryResumeWithException(java.lang.Throwable)>
kotlinx.coroutines.CancellableContinuation$DefaultImpls
    public static java.lang.Object tryResume$default(kotlinx.coroutines.CancellableContinuation, java.lang.Object, java.lang.Object, int, java.lang.Object)
    {
        java.lang.Object $r0, $r1, $r3;
        kotlinx.coroutines.CancellableContinuation $r2;
        int $i0;
        java.lang.UnsupportedOperationException $r4;

        $r2 := @parameter0: kotlinx.coroutines.CancellableContinuation;

        $r1 := @parameter1: java.lang.Object;

        $r3 := @parameter2: java.lang.Object;

        $i0 := @parameter3: int;

        $r0 := @parameter4: java.lang.Object;

        if $r0 != null goto label2;

        $i0 = $i0 & 2;

        if $i0 == 0 goto label1;

        $r3 = null;

     label1:
        $r1 = interfaceinvoke $r2.<kotlinx.coroutines.CancellableContinuation: java.lang.Object tryResume(java.lang.Object,java.lang.Object)>($r1, $r3);

        return $r1;

     label2:
        $r4 = new java.lang.UnsupportedOperationException;

        specialinvoke $r4.<java.lang.UnsupportedOperationException: void <init>(java.lang.String)>("Super calls with default arguments not supported in this target, function: tryResume");

        throw $r4;
    }

