kotlin.coroutines.jvm.internal.CompletedContinuation
<kotlin.coroutines.jvm.internal.CompletedContinuation: kotlin.coroutines.jvm.internal.CompletedContinuation INSTANCE>
    static void <clinit>()
    {
        kotlin.coroutines.jvm.internal.CompletedContinuation $r0;

        $r0 = new kotlin.coroutines.jvm.internal.CompletedContinuation;

        specialinvoke $r0.<kotlin.coroutines.jvm.internal.CompletedContinuation: void <init>()>();

        <kotlin.coroutines.jvm.internal.CompletedContinuation: kotlin.coroutines.jvm.internal.CompletedContinuation INSTANCE> = $r0;

        return;
    }

    private void <init>()
    {
        kotlin.coroutines.jvm.internal.CompletedContinuation $r0;

        $r0 := @this: kotlin.coroutines.jvm.internal.CompletedContinuation;

        specialinvoke $r0.<java.lang.Object: void <init>()>();

        return;
    }

    public kotlin.coroutines.CoroutineContext getContext()
    {
        kotlin.coroutines.jvm.internal.CompletedContinuation $r0;
        java.lang.IllegalStateException $r1;
        java.lang.String $r2;

        $r0 := @this: kotlin.coroutines.jvm.internal.CompletedContinuation;

        $r1 = new java.lang.IllegalStateException;

        $r2 = "This continuation is already complete";

        $r2 = virtualinvoke $r2.<java.lang.Object: java.lang.String toString()>();

        specialinvoke $r1.<java.lang.IllegalStateException: void <init>(java.lang.String)>($r2);

        throw $r1;
    }

    public void resumeWith(java.lang.Object)
    {
        kotlin.coroutines.jvm.internal.CompletedContinuation $r0;
        java.lang.String $r1;
        java.lang.Object $r2;
        java.lang.IllegalStateException $r3;

        $r0 := @this: kotlin.coroutines.jvm.internal.CompletedContinuation;

        $r2 := @parameter0: java.lang.Object;

        $r3 = new java.lang.IllegalStateException;

        $r1 = "This continuation is already complete";

        $r1 = virtualinvoke $r1.<java.lang.Object: java.lang.String toString()>();

        specialinvoke $r3.<java.lang.IllegalStateException: void <init>(java.lang.String)>($r1);

        throw $r3;
    }

    public java.lang.String toString()
    {
        kotlin.coroutines.jvm.internal.CompletedContinuation $r0;

        $r0 := @this: kotlin.coroutines.jvm.internal.CompletedContinuation;

        return "This continuation is already complete";
    }

